name: Unit Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types:
      types: [assigned, opened, synchronize, reopened]
  pull_request_review:
    types: [edited, dismissed]
jobs:
  build-node:
    name: Build node application
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - run: node --version
        name: Check Node Version
      - run: npm --version
        name: Check NPM Version
      - uses: actions/checkout@v2
        name: Code Checkout
      - run: npm install
        name: Install NPM packages
      - run: npx hardhat test
        name: Run Unit Tests

